---
  - name: Playbook lineinfile
    hosts: local

    tasks:
      - name: Ajout du certificat
        lineinfile:
                path: require.conf
                line: "Require expr \"'%{SSL_CLIENT_I_DN}:%{SSL_CLIENT_S_DN_CN}:%{SSL_CLIENT_M_SERIAL}' == 'CN=xxx,OU=xxx,O=xxx,C=xx:{{ prenom }} {{ nom }}:{{ certificat }}'\""
